# An Introduction to Numpy

In [1]:
# Importing Numpy
import numpy as np

In [2]:
# Creating 2 lists

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [3]:
# Use index to find out the position of a value in a list
height.index(1.79)

4

#### Creating Arrays

In [4]:
np_height = np.array(height)
np_weight = np.array(weight)

In [5]:
print(np_height)
print(np_weight)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [6]:
# Calculating Body Mass Index

bmi = np_weight / np_height ** 2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


**_Numpy Subsetting_**

In [7]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [8]:
# Find out the second position of bmi

bmi[1]

20.97505668934241

In [9]:
# boolean output of comparing values
bmi > 23

array([False, False, False,  True, False])

In [10]:
# Subsetting to find out exact values
np.round(bmi[bmi > 23], 2)

array([24.75])

**_2D Numpy Array_**

In [11]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [12]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [14]:
for x in np.nditer(np_baseball):
    print(x)

180.0
78.4
215.0
102.7
210.0
98.5
188.0
75.2


In [24]:
# Print out the shape of np_baseball
# it will show how many rows and columns are there
print(np_baseball.shape)
type(np_baseball)

(4, 2)


numpy.ndarray

In [27]:
# Print out the 3rd row
np_baseball[2, :]

array([210. ,  98.5])

In [30]:
# Select the entire 2nd column
np_baseball[:, 1]

array([ 78.4, 102.7,  98.5,  75.2])

In [28]:
# Print out 2nd row and 2nd column

np_baseball[1, 1]

102.7

In [31]:
conversion = np.array([0.0254, 0.453592])

In [32]:
print(np_baseball * conversion)

[[ 4.572     35.5616128]
 [ 5.461     46.5838984]
 [ 5.334     44.678812 ]
 [ 4.7752    34.1101184]]


#### Numpy Summary Statistics

**_Generate Data_**

In [38]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [39]:
# paste this two lists in two coloumns
np_city = np.column_stack((height, weight))

In [41]:
np_city.mean()

31.143865

In [42]:
print(np_city)

[[ 1.64 51.65]
 [ 1.85 78.42]
 [ 1.79 73.89]
 ...
 [ 1.75 65.16]
 [ 2.07 68.26]
 [ 1.86 50.05]]


In [54]:
# Average of weight
average_weight = np.round(np.mean(np_city[:, 1]), 2)
print("Average: " + str(average_weight))

Average: 60.54


In [55]:
median_weight = np.round(np.median(np_city[:, 1]), 2)
print("Median: " + str(median_weight))

Median: 60.28


In [57]:
# Print out Standard Deviation
std_dev = np.round(np.std(np_city[:, 1]), 2)
print("Standard deviation: " + str(std_dev))

Standard deviation: 15.25


In [59]:
# Print out correlation between first and second column.
corr = np.corrcoef(np_city[:, 0], np_city[:, 1])
print("Correlation: " + str(corr))

Correlation: [[ 1.00000000e+00 -1.23669255e-04]
 [-1.23669255e-04  1.00000000e+00]]


In [ ]:
# Convert positions and heights to numpy arrays: np_positions, np_heights

np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights

gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights

other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))